### ISSUE TITLE
Jigsaw / disjointed month support

### ISSUE THREAD

**Issue by euphoria** [patientslikeme/react-calendar-heatmap#13]
It would be useful to be able to support the Jigsaw / disjointed month style found on GitLab's activity graphs.  You can see an example at https://gitlab.com/u/rymai

**Comment by iqnivek** [comment]
good idea - I'll look into that at some point!

**Comment by iqnivek** [comment]
Sorry @euphoria, don't think we'll likely be supporting this after all.
