### ISSUE TITLE
Calender Heatmap not working

### ISSUE THREAD

**Issue by ankitrg** [patientslikeme/react-calendar-heatmap#22]
I am using this component to render heatmap, but I am unable to do so. I think the component is not accepting my dataset. I have also tried with fixed dataset.

Here is what my component looks like:

```
<CalendarHeatmap
                  values={this.createTimelineAnalysisData()}
                  showOutOfRangeDays={false}
/>
```

This will just render a black heatmap with 6 months, it must be the default I think.

**Comment by iqnivek** [comment]
what do your values look like - can you give an example? it should be an
array of objects that each have a 'date' attribute. additionally, you'll
need to add some css to make the colors not be the default svg black color
- take a look at the readme to see how to get started with some sample css.
let me know if you have further questions!

**Comment by iqnivek** [comment]
Here's a minimal setup of react-calendar-heatmap with create-react-app on CodeSandbox, which should hopefully help show how things are set up: https://codesandbox.io/s/73mk9wlyx
