### ISSUE TITLE
Add mouseOver / mouseLeave props to squares

### ISSUE THREAD

**Issue by stevelacy** [patientslikeme/react-calendar-heatmap#26]
Request, add mouse events to the squares.
https://github.com/patientslikeme/react-calendar-heatmap/blob/master/src/index.jsx#L196

```js
    return (
      <rect
        key={index}
        width={SQUARE_SIZE}
        height={SQUARE_SIZE}
        x={x}
        y={y}
        title={this.getTitleForIndex(index)}
        className={this.getClassNameForIndex(index)}
        onClick={this.handleClick.bind(this, this.getValueForIndex(index))}
        onMouseOver={(e) => this.props.handleMouseOver ? this.props.handleMouseOver(e, value) : null}
        onMouseLeave={(e) => this.props.handleMouseLeave ? this.props.handleMouseLeave(e, value) : null}
        {...this.getTooltipDataAttrsForIndex(index)}
      />
    );
```
Pass the value and date of that square and it's pointer event (for x/y coordinates).
This will enable the parent component to get the 'tooltip' event as a prop in a more react way, instead of using a jquery style selector.
If you would prefer not to have ternaries I can change them.

I can send a PR as I have been using my fork for a while.

**Comment by arvindkumarc** [comment]
This should be a simple enough change to include, it would allow us to not rely on jquery/bootstrap based tooltips.
Add me as a collab, I can contribute and close this out.

**Comment by andreysaleba** [comment]
Hey, I've added PR for this #39
