### ISSUE TITLE
Feature Show Days

### ISSUE THREAD

**Issue by DavidSichau** [patientslikeme/react-calendar-heatmap#29]
It would be nice if one could additionally display the days on the left side. Like on github.

like Mon, Wed and Fri or so.

**Comment by andreysaleba** [comment]
I'll try to submit PR with this feature in the next few days

**Comment by andreysaleba** [comment]
Hey, I've submitted PR with this feature implementation.
Can you check it? #37

**Comment by andreysaleba** [comment]
It's done now, I guess this can be closed
