### ISSUE TITLE
React Bootstrap Tooltips?

### ISSUE THREAD

**Issue by VictorChen** [patientslikeme/react-calendar-heatmap#32]
Is there a good way to hook up tooltips if we're currently using React-Bootstrap?

eg:
https://react-bootstrap.github.io/components.html#tooltips

**Comment by cassiopagnoncelli** [comment]
Semantic UI is also a good pick to go

**Comment by scotthelps** [comment]
@VictorChen add this prop to your CalendarHeatmap component.

```php
transformDayElement={(rect, value, index) => {
  const tooltip = (
    <Tooltip id="tooltip">{value ? value.date : ''}</Tooltip>
  );
  return (
    <OverlayTrigger placement="top" overlay={tooltip}>
      {rect}
    </OverlayTrigger>
   );
}}
```

**Comment by VictorChen** [comment]
@scotthelps Nice!! did not know about `transformDayElement` prop, thanks!

**Comment by grahambryan** [comment]
@cassiopagnoncelli could you post a snippet of how you got the tooltip to work with semantic-ui-react popup component?

**Comment by cassiopagnoncelli** [comment]
@grahambryan Honestly I couldn't, it was a mere suggestion. However it seems to be as easy as wrapping Semantic UI's <Popup /> around 

https://github.com/patientslikeme/react-calendar-heatmap/blob/0fb7a61638addea1e1d9254b55a777748a716c9d/src/index.jsx#L251

**Comment by grahambryan** [comment]
@cassiopagnoncelli Thanks! I ended up going with react-tooltip 

`  <CalendarHeatmap
                    endDate={new Date('2018-01-01')}
                    startDate={this.state.startDate}
                    values={this.state.values}
                    onClick={this.onClick}
                    classForValue={(value) => {
                        if (!value) {
                          return 'color-empty';
                        }
                        return `color-github-${value.count}`;
                      }}
                    tooltipDataAttrs={customTooltipDataAttrs}  
                />
                <ReactTooltip
                    type='warning' 
                    effect='solid'                  
                />`

`const customTooltipDataAttrs = (value) => ({
    'data-tip': value.date === null ? '' : value.status + ' on ' + value.date
});`

 and using a controlled semantic-UI-react modal that will open onClick and give the user more detailed information about the day clicked.
