### ISSUE TITLE
Upgrade to latest React

### ISSUE THREAD

**Issue by easingthemes** [patientslikeme/react-calendar-heatmap#34]
Hi,
From `react v15.5` some dependencies has changed:

1. PropTypes are now separate package `prop-types`.
https://facebook.github.io/react/warnings/dont-call-proptypes.html

2. `react-addons-test-utils` are deprecated.
https://www.npmjs.com/package/react-addons-test-utils

3. `enzyme` has changed because of that.
https://github.com/airbnb/enzyme/issues/976

So this component needs update.

I'm already on it, creating PR in few minutes.

**Comment by okize** [comment]
Thank you @easingthemes!

Issue fixed by https://github.com/patientslikeme/react-calendar-heatmap/pull/35
