### ISSUE TITLE
Not an issue. Thanks for this component!

### ISSUE THREAD

**Issue by Anveio** [patientslikeme/react-calendar-heatmap#44]
Using your source code, I was able to create a similar component adapted to my own needs for use in a TypeScript + Redux + Immutable.js project. (If anyone wants to see what that looks like: https://github.com/Anveio/mturk-engine/blob/master/src/components/Calendar/CalendarHeatMap.tsx )

The end result: https://i.imgur.com/3CSIXc5.png

This was my first introduction to using SVG and I'm happy with how it turned out (and I have a lot to learn 😅).

**Comment by okize** [comment]
that looks awesome @Anveio!
