### ISSUE TITLE
classForValue not working

### ISSUE THREAD

**Issue by vikkya** [patientslikeme/react-calendar-heatmap#64]
I cloned the repo  and the color for the heatmap is not wokring as shown in the demo.  im getting black instead. (PFA).
![repo](https://user-images.githubusercontent.com/26187350/33607502-59d01322-d9e7-11e7-89cb-594b6f5649f0.png)

can u please tell me what is wrong here.

**Comment by tejaser** [comment]
Its missing d3js dependency in the package.json file.  you can add the same and get it to work.  I have submitted a [pull request#65](https://github.com/patientslikeme/react-calendar-heatmap/pull/65) for the same

**Comment by tejaser** [comment]
I worked with the developer, it seems the problem is with his windows machine.  the pull request was not required.  So I have closed the pull request.  I have suggested him to use online editor to verify the issue.

**Comment by okize** [comment]
@vikkya could you provide some more details? are you seeing any console errors?

**Comment by iqnivek** [comment]
Closing this as we haven't heard anything about it for a while. If you still see this issue, please take a look at the [codesandbox example](https://codesandbox.io/s/73mk9wlyx) and see if you can fork it to have a minimal example that reproduces the issue. Thanks!
