### ISSUE TITLE
Fix travis-ci failure on node 5

### ISSUE THREAD

**Issue by iqnivek** [patientslikeme/react-calendar-heatmap#9]
node 5 does work fine locally, but failing on travis:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/129546876/log.txt

**Comment by theptrk** [comment]
Dont know why its failing but here is the first error message: 

Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

**Comment by theptrk** [comment]
The other error messages are probably because the above error is causing installation/bundling issues

**Comment by iqnivek** [comment]
Builds are working now, closing.
