### ISSUE TITLE
Blocks to represent weeks not days

### ISSUE THREAD

**Issue by benjamindesilva** [patientslikeme/react-calendar-heatmap#95]
Hi,

Is there a possibility for the blocks to represent weeks and not days? I'm looking to build out a vertical calendar heat map displaying a year at a time. So in order to save screen space, I would like each block to represent a week (ie: each row of blocks would be a month).
Eg: 
[][][][][] August
[][][][][] July
[][][][][] June
etc...

It would be wonderful if this was possible as I need to multi-select blocks representing weeks/months in order to select a date-range for a chart.

Is this possible with the current rect-calendar-heatmap control?

**Comment by iqnivek** [comment]
Hi @benjamindesilva! This wouldn't be possible right now, and the suggested functionality seems divergent enough that it'd probably be better just to fork and roll your own.
