### ISSUE TITLE
Running inside <StrictMode> gives warning about componentWillReceiveProps

### ISSUE THREAD

**Issue by anajavi** [patientslikeme/react-calendar-heatmap#96]
I just tested running react-calendar-heatmap inside a strict mode tree (https://reactjs.org/docs/strict-mode.html).
It gives the following warning:
```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at app.js:59)
    in App
    in AppContainer (at main.js:17)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: CalendarHeatmap

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

getDerivedStateFromProps cannot be used in React 16.3, so this can be resolved with:
1. raising the peerDependency version of React
2. **or** using componentDidMount and componentDidUpdate to do the same thing

Which one is preferred solution?

**Comment by evan-007** [comment]
thanks @anajavi -- my first reaction is to release a version using `componentDidUpdate` for now and then bump the react dep in v2.0.0.
